version: '3.8'
services:
  mongodb_sync:
    build: .
    volumes:
      - ./logs:/app/logs
    environment:
      - RDS_HOST=trinity-db.cbke280aq027.ap-northeast-2.rds.amazonaws.com
      - RDS_USER=ec2-user
      - RDS_PASSWORD=profect1234*
      - RDS_DATABASE=trinity-db
      - RDS_PORT=3306
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_USER=ai_user
      - MONGO_PASSWORD=profect1234*
      - MONGO_DATABASE=ai_db
      - MONGO_COLLECTION=recsys_data
      - SYNC_INTERVAL_MINUTES=60
    restart: always
    networks:
      - sync_network

networks:
  sync_network:
    driver: bridge